### ISSUE TITLE
Trouble running pyportus or making it

### ISSUE THREAD

**Issue by PrinceS17** [ccp-project/portus#100]
Hi, I am trying to get pyportus working but there is an issue. I tested two ways: 1) make portus manually; 2) directly pip install portus and use it. 

During 1), I found that I cannot make ipc_latency or test-ipc, and the error is like:

![image](https://user-images.githubusercontent.com/26733252/141667372-a63c67ed-348d-4956-84f2-54a67b78e506.png)

I tried ignoring it and go with `sudo env PATH=$PATH python setup.py develop`, and I ensured that the built version is what I used by ` sudo /ccp/.venv/bin/python aimd.py`, and I got the error below

![image](https://user-images.githubusercontent.com/26733252/141667415-97f5da03-88eb-4f1d-9ba6-f64eb45af692.png)

Using 2), I tried running aimd.py in the example folder of latest portus, and I got the same error above.

And I found the fault location in src/serialize/create.rs:

![image](https://user-images.githubusercontent.com/26733252/141667465-3786482f-9116-4c36-a2e8-0988bdba1939.png)

It seems something in the rust part which I am not familiar with. Any idea on the possible cause? Thanks.

**Comment by akshayknarayan** [comment]
I am guessing you are using the eval-scripts repository's setup, so I think this is really a bug in that repository not being up to date. For example, `setup.py` no longer exists (in favor of maturin): https://github.com/ccp-project/portus/tree/master/python. 

Given you are getting a serialization error, it is probably due to relatively recent serialization changes explained [here](https://github.com/ccp-project/ccp-kernel/blob/master/README.md?plain=1#L8). I would suggest making sure you are using the latest ccp-kernel (e.g., after your recent PR) as well as portus 0.6.1.

Another suggestion is to use linux kernel 5.4. The eval-scripts repository uses the `tcp_probe` kernel module for some parts of the paper's experiments, which was removed in later versions of the kernel, and that is why the vagrantfile specifies an older OS. This almost certainly doesn't matter for developing on ccp today.

**Comment by PrinceS17** [comment]
Yes, I think the outdated version should be the problem. I've just managed to run aimd.py with portus 0.6.1 by just pip installation. The whole CCP doesn't work though as the kernel is 4.15. I believe I am really close. Thank you for your help!

**Comment by akshayknarayan** [comment]
Great!

**Comment by PrinceS17** [comment]
Sorry to disturb you again, but I just tried ccp in a VirtualBox VM using Ubuntu 20.04 with kernel 5.11, portus 0.6.1, and this time the ccp-kernel doesn't work again. When I load the kernel, dmesg prints "could not send ready message: -3", and -3 should be ESRCH, i.e. no such process, occurring during the nl_sendmsg(). And when I run some user program like BBR, the flow has really low throughput and dmesg shows there are 2 connections (a normal one, and its reverse), which looks weird. I tried kernel 5.4 but it's still the same. Any idea?

**Comment by akshayknarayan** [comment]
No problem, `-3` means what you said: no one was listening to the other side of the netlink message. One consequence of the thing I said before is that `ccp-kernel` does (now) expect that the userspace CCP agent is running before the kernel module is loaded (see instructions here: https://github.com/ccp-project/portus/issues/99#issuecomment-963395466, the call to nl_sendmsg is here: https://github.com/ccp-project/libccp/blob/master/ccp.c#L66). 

Since you are trying to use bbr, which is on portus 0.5 (I can update it in the next day or so, but a PR would also be welcome), try using the portus-0.5-compat branch as suggested [here](https://github.com/ccp-project/ccp-kernel/blob/master/README.md?plain=1#L8). Another way to check this is to try using the [Reno/Cubic implementations](https://github.com/ccp-project/generic-cong-avoid).

**Comment by akshayknarayan** [comment]
I updated bbr for portus 0.6 just now: https://github.com/ccp-project/bbr/commit/f4b6d13a6ab384cc1aad8fb1a84e5aeb0409416d

**Comment by PrinceS17** [comment]
Cool. I actually tried starting the user program before ccp-kernel. That gave me "libccp fallback timed out" with loopback test, and I thought it didn't work. But your reply made me realize that it's the high speed of loopback that should be the problem, which makes the libccp just normally timed out. After I use Mahimahi, it all works now.
Btw I've managed to use pyportus in with this new VM, so the portus part is just fine. Thank you for your help!

**Comment by minnamu** [comment]
> Yes, I think the outdated version should be the problem. I've just managed to run aimd.py with portus 0.6.1 by just pip installation. The whole CCP doesn't work though as the kernel is 4.15. I believe I am really close. Thank you for your help!

Hello,how to install portus 0.6.1 via pip,I failed to install using PIP install portus==0.6.1.
![image](https://user-images.githubusercontent.com/97097650/148701047-69bb8818-b26d-4b2b-beb6-2face4a83556.png)
