### ISSUE TITLE
How to install and use CCP？There seem to be multiple versions of the tutorial.

### ISSUE THREAD

**Issue by intothesea** [ccp-project/portus#104]
I have noticed that there are multiple versions of CCP tutorials available at https://ccp-project.github.io/ccp-guide/setup/index.html and https://github.com/ccp-project/portus/tree/master/python, which has led to some confusion on my part. For example, I have come across different packets such as "portus" and "pyportus," and I'm uncertain about which one to install.

I would like to request a complete and unified set of installation instructions for CCP, starting with the installation of Rust. Having a clear, step-by-step guide from the beginning would greatly help users like me who are new to CCP and want to set up a consistent environment.

Thank you for your assistance in addressing these concerns.

**Comment by akshayknarayan** [comment]
Hi, thanks for your interest in CCP.
It's hard for me to tell what exactly your point of confusion is: there cannot exist a "unified" set of installation instructions, since it is possible to use CCP for two distinct purposes:
1. congestion control algorithm development on some datapath
2. adding CCP support to a datapath to enable existing CCP-based congestion control implementations to work.

The guide that you linked to, https://ccp-project.github.io/ccp-guide/setup/index.html, is a good place to start if (1) is your goal. API documentation for writing congestion control implementations in Rust is available at https://docs.rs/portus/latest/portus/.
You also mentioned pyportus, or python bindings to the ccp library, which makes it possible to write congestion control implementations in python. To use pyportus, it's necessary to install the python library: that is what the directions at https://github.com/ccp-project/portus/blob/master/python/README.md are for. The python bindings also have a different API, which that Readme gives an overview of.

If your goal is to add CCP support to an existing datapath, https://github.com/ccp-project/libccp/blob/master/README.md is the documentation you want. It would probably also help to look at how the linux kernel datapath integration was implemented; that is at https://github.com/ccp-project/ccp-kernel.

**Comment by intothesea** [comment]
> Hi, thanks for your interest in CCP. It's hard for me to tell what exactly your point of confusion is: there cannot exist a "unified" set of installation instructions, since it is possible to use CCP for two distinct purposes:
> 
> 1. congestion control algorithm development on some datapath
> 2. adding CCP support to a datapath to enable existing CCP-based congestion control implementations to work.
> 
> The guide that you linked to, https://ccp-project.github.io/ccp-guide/setup/index.html, is a good place to start if (1) is your goal. API documentation for writing congestion control implementations in Rust is available at https://docs.rs/portus/latest/portus/. You also mentioned pyportus, or python bindings to the ccp library, which makes it possible to write congestion control implementations in python. To use pyportus, it's necessary to install the python library: that is what the directions at https://github.com/ccp-project/portus/blob/master/python/README.md are for. The python bindings also have a different API, which that Readme gives an overview of.
> 
> If your goal is to add CCP support to an existing datapath, https://github.com/ccp-project/libccp/blob/master/README.md is the documentation you want. It would probably also help to look at how the linux kernel datapath integration was implemented; that is at https://github.com/ccp-project/ccp-kernel.

Thank you very much for your response! In fact, I'd like to use CCP to add a new AI-based congestion control algorithm to a TCP connection, so I should use the **pyportus** package. I also want to confirm my installation steps:

1.Install Rust
2. Install ccp-kernel:
    a. git clone https://github.com/ccp-project/ccp-kernel.git
    b. git submodule update --init --recursive
    c. cd ccp-kernel && make
    d. sudo ./ccp_kernel_load ipc=0
3.pip install pyportus
4.sudo python [alg].py
5.Use tools like ‘iperf -Z ccp xxxx’ to start a TCP connection for experiments.

Are they all correct?

**Comment by akshayknarayan** [comment]
Yes, these steps should work to run a python congestion control implementation. Note that you will need the linux headers package for your environment to compile the ccp-kernel kernel module. On debian/ubuntu this would be `apt install linux-headers-$(uname -r)`.

One thing to note is that if you use virtualenv/venv, pip will install pyportus in a location that `sudo python` does not know about, so you will need to do `sudo ./<venv>/python [alg].py` as per https://github.com/ccp-project/portus/blob/master/python/README.md#setup.

**Comment by intothesea** [comment]
> Yes, these steps should work to run a python congestion control implementation. Note that you will need the linux headers package for your environment to compile the ccp-kernel kernel module. On debian/ubuntu this would be `apt install linux-headers-$(uname -r)`.
> 
> One thing to note is that if you use virtualenv/venv, pip will install pyportus in a location that `sudo python` does not know about, so you will need to do `sudo ./<venv>/python [alg].py` as per https://github.com/ccp-project/portus/blob/master/python/README.md#setup.

I have successfully run the AIMD.py demo! Thanks a lot!
